### ISSUE TITLE
Instructions for how to use these pre-build dylibs 

### ISSUE THREAD

**Issue by lnshi** [vodianyk/libtensorflow-cpu-darwin-arm64#1]
Hi @vodianyk, thanks a lot for building these TF dylibs for M1.

But i am having troubles to figure out how should i properly utilise them with `cargo`, could u pls help to provide some instructions to show how to prevent `cargo` building the `tensorflow-rust` from source?

**Comment by ramonsf29** [comment]
Hi, thanks for sharing, I would like to ask if Tensorflow Lite is part of the buildings you share.

Best regards

**Comment by lnshi** [comment]
i eventually make everything work on my M1, if anyone still stuck on this issue, i build a gist [here](https://gist.github.com/lnshi/eb3dea05d99daba5c932bbc786cc3701), should be able to help u out 🎉🎉🎉
